server:
  error:
    include-message: always

spring:
  application:
    name: default
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
